### ISSUE TITLE
Проблема с оптимизацией

### ISSUE THREAD

**Issue by ilyasidorchik** [ilyasidorchik/sdamgia-introtask-alyona#1]
Кажется, у нас проблема с оптимизацией.

Чтобы понять её, добавь `console.log('render')` здесь:
https://github.com/ilyasidorchik/sdamgia-homework-alyona/blob/fb249696cb3ddadfc3669cead381329aae147273/src/components/SearchForm.js#L5

Затем напиши что-нибудь в поисковом поле. Что будет выведено в консоли?

**Comment by alyonausoeva** [comment]
![image](https://user-images.githubusercontent.com/43846641/94337884-7cdb3580-fff6-11ea-8c2a-f3eddf076137.png)

**Comment by ilyasidorchik** [comment]
Да. Ты печатаешь → изменяешь стейт. А как только изменяется стейт, компонент перерендеривается. Это ок, такой принцип работы.

Но посмотри на функцию-обработчик ввода:
https://github.com/ilyasidorchik/sdamgia-introtask-alyona/blob/fb249696cb3ddadfc3669cead381329aae147273/src/components/SearchForm.js#L6

Она создаётся заново при каждом перерендере компонента. Это не дело. Как оптимизировать?

Для дополнительной мотивации. Такой вопрос мне задали на собеседовании в Ситимобиле.
